export default [
  {
    name: "Wealthsimple",
    position: "Senior Seftware Engineer",
    from: "Oct. 2020",
    to: "Present",
    logo: "/imgs/wealthsimple.webp",
    relevant: true,
    achievements: [
      "Device Intelligence and client awareness of device activity"
    ],
  },
  {
    name: "Wonolo: In-Demand Staffing Solutions for Businesses",
    position: "Full Stack Software Engineer",
    from: "Jan. 2020",
    to: "Sep. 2021",
    logo: "/imgs/wonolo.webp",
    relevant: true,
    achievements: [
      "implemented data synchronization with Salesforce Integration",
      "Migrated Rails pages to React.js App",
      "Improved global Search performance from 24s per query to 400ms",
    ],
  },
  {
    name: "JEWLR: Personalized Jewelry",
    position: "Full Stack Software Engineer",
    from: "Oct. 2018",
    to: "Jan. 2020",
    logo: "/imgs/jewlr.svg",
    relevant: true,
    achievements: [
      "Implemented server-to-server communication API reducing number of calls by 50%",
      "Implemented single checkout API to process multiple types of payments",
      "Developed Tax API to fetch tax rates depending on location",
      "Created React.js modal component, replacing all JQuery modals in the application",
    ],
  },
  {
    name: "EventIQ inc. (Currently RightLabs inc.)",
    position: "Full Stack Software Engineer",
    from: "Oct. 2014",
    to: "Sep. 2018",
    logo: "/imgs/eventiq.png",
    relevant: false,
    achievements: [
      "Designed application Architecture and UI design",
      "Payment gateways integration",
      "Developing Front and Back end functionality of application",
      "Providing testing of server and client side",
    ],
  },
  {
    name: "LogiSense Ltd. - Information Technology & Services",
    position: "Web Developer",
    from: "Feb. 2014",
    to: "Sep. 2018",
    logo: "/imgs/logisense.png",
    relevant: false,
    achievements: [
      "Maintained specific parts of application",
      "Worked on code optimization and refactoring",
      "Participated in international meetings with parent company and chief developers",
      "Contributed to a angular-ui-grid repository as a part of a job",
    ],
  },
  {
    name: "Inkubasia ",
    position: "Web Developer",
    from: "May. 2013",
    to: "Sep. 2013",
    logo: "/imgs/inkubasia.png",
    relevant: false,
    achievements: [
      "WordPress and Joomla template customizations",
      "Design templates and plugins",
      "Installing and customizing plugins",
      "Managing content",
      "Developing applications from design prototypes and documentation",
    ],
  },
];
